<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "#{rerun_opts} --format rerun --out rerun.txt --strict --tags ~@wip"
%>
default: --tags ~@wip
//default: <%= std_opts %> commented this out to fix cuke not working from rake - see http://stackoverflow.com/questions/2620983/cucumber-steps-not-automatically-loaded-when-running-features
wip: --tags @wip:3 --wip features

autotest-all: --color --require features --require lib --format progress features
autotest: --color --require features --require lib features